# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: The Horenberger Zone
author:
  name: Beau Horenberger
description: Cite me in your thesis

show_excerpts: true

header_pages:
 - index.md
 - diary.md
 - caravan.md
 - llamaspace.md
 - about.md
 - contact.md

# Set this to true to get LaTeX math equation support
use_math: true

# Everything below here can be ignored, unless you want to change the theme entirely
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-remote-theme

remote_theme: horenbergerb/minima

minima:
  date_format: "%b %-d, %Y"
  skin: solarized-light
  social_links:
    twitter: BeauHorenberger
    github: horenbergerb
    linkedin: beau-horenberger-875487164

google_analytics: G-JRSVEQLDK4

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
